package com.example.demo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="demo_movie")
public class Movie {
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	String id;
	
	@DynamoDBAttribute(attributeName="genre")
	String genre;
	@DynamoDBAttribute(attributeName="bookingStatus")
	String bookingStatus;
	@DynamoDBAttribute(attributeName="title")
	String title;
	@DynamoDBAttribute(attributeName="releaseDate")
	String releaseDate;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getGenre() {
		return genre;
	}
	public void setGenre(String genre) {
		this.genre = genre;
	}
	public String getBookingStatus() {
		return bookingStatus;
	}
	public void setBookingStatus(String bookingStatus) {
		this.bookingStatus = bookingStatus;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getReleaseDate() {
		return releaseDate;
	}
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}
	public Movie(String id, String genre, String bookingStatus, String title, String releaseDate) {
		super();
		this.id = id;
		this.genre = genre;
		this.bookingStatus = bookingStatus;
		this.title = title;
		this.releaseDate = releaseDate;
	}
	
	public Movie() {
		super();
		
	}
	@Override
	public String toString() {
		return "Movie [id=" + id + ", genre=" + genre + ", bookingStatus=" + bookingStatus + ", title=" + title
				+ ", releaseDate=" + releaseDate + "]";
	}
	
	
}
